---
- hosts: splunk_servers
  become: yes
  tasks:

    - name: Ensure the directory /opt/splunk/files exists
      file:
        path: /opt/splunk/files/
        state: directory

    - name: Extract splunk-install-files.tar.gz to /opt/splunk/files/
      unarchive:
        src: /path/to/your/local/splunk-install-files.tar.gz
        dest: /opt/splunk/files/
        remote_src: no

    - name: Move all content from /app/splunkforwarder/splunk to /app/splunkforwarder/
      command: mv /app/splunkforwarder/splunk/* /app/splunkforwarder/
      args:
        removes: /app/splunkforwarder/splunk/*
      ignore_errors: yes # This will ignore errors if there are no files to move. Remove this if you want to fail in such a case.

    - name: Remove the directory /app/splunkforwarder/splunk
      file:
        path: /app/splunkforwarder/splunk
        state: absent

    - name: Install Splunk
      command: /opt/splunk/files/splunkforwarder/bin/splunk start --accept-license
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: Create Splunk service
      command: /opt/splunk/files/splunkforwarder/bin/splunk enable boot-start
      become: yes
      become_method: sudo

    - name: Ensure Splunk service is started
      service:
        name: Splunkd
        state: started

    - name: Get Splunk Status
      command: /opt/splunk/files/splunkforwarder/bin/splunk status
      register: splunk_status
      changed_when: false

    - debug:
        msg: "{{ splunk_status.stdout_lines }}"

    - name: Check if Splunk is installed
      command: which splunk
      register: splunk_installed
      failed_when: splunk_installed.rc != 0
      changed_when: false

    - debug:
        msg: "Splunk is installed at {{ splunk_installed.stdout }}"

    - name: Get version of Splunk forwarder
      command: /opt/splunk/files/splunkforwarder/bin/splunk version
      register: splunk_version
      changed_when: false

    - debug:
        msg: "Splunk Forwarder version is: {{ splunk_version.stdout }}"

---
- name: Check Splunk Installation and Status
  hosts: splunk_servers
  tasks:
    - name: Check if Splunk is installed
      stat:
        path: "/opt/splunk/bin/splunk"
      register: splunk_bin

    - name: Fail if Splunk is not installed
      fail:
        msg: "Splunk is not installed on this host"
      when: not splunk_bin.stat.exists

    - name: Check if Splunk is running
      command: "/opt/splunk/bin/splunk status"
      register: splunk_status
      changed_when: False
      ignore_errors: True

    - name: Print Splunk status
      debug:
        msg: "{{ splunk_status.stdout }}"
      when: splunk_status.rc == 0

    - name: Print error if Splunk is not running
      debug:
        msg: "Splunk does not appear to be running!"
      when: splunk_status.rc != 0
