---
- name: Stop Splunk
  hosts: splunk_servers  # This should be the group where your Splunk servers are defined in your inventory
  tasks:

    - name: Navigate to Splunk Directory and Stop Splunk
      command:
        cmd: ./splunk stop
        chdir: /app/splunk/bin
      become: yes  # This is to run the command as sudo. Remove or modify if not necessary.

    - name: Verify Splunk Has Stopped
      shell: ps aux | grep -v grep | grep splunk
      register: splunk_process
      failed_when: splunk_process.stdout != ''
      changed_when: false  # This task is not changing any state, it's just for verification.
