- name: Check Splunk Status
  hosts: all
  tasks:
    - name: Execute splunk status command
      shell: /app/splunkforwarder/bin/splunk status
      register: splunk_status_output
      ignore_errors: yes  # Ignore errors in case Splunk is not installed or running

    - name: Check if Splunk is running
      fail:
        msg: "Splunk is not running or splunkd/splunk helpers are not running."
      when: "'splunkd' not in splunk_status_output.stdout or 'splunk helpers' not in splunk_status_output.stdout"

    - name: Display Splunk Status
      debug:
        var: splunk_status_output.stdout_lines

    - name: Set status to success
      set_fact:
        status: "Success"

- name: Finish Playbook
  hosts: all
  tasks:
    - name: Finish Playbook Execution
      meta: end_play
      when: status == "Success"
