- name: Execute Shell Script and Clean Logs
  hosts: your_target_hosts  # Specify your target hosts here
  vars:
    interval: "{{ interval }}"  # This variable will be provided from Ansible Tower

  tasks:
    - name: List all log files in /app/splunk/script/
      shell: "ls /app/splunk/script/*.log"
      register: log_files
      ignore_errors: yes  # Ignore errors if no log files exist

    - name: Display list of log files
      debug:
        msg: "Log files: {{ log_files.stdout_lines }}"

    - name: Clean all .log files from /app/splunk/script/
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ log_files.stdout_lines }}"
      when: log_files.stdout_lines | length > 0  # Execute only if log files are present

    - name: Execute splunk_sar_log.sh script
      shell: "/app/splunk/script/splunk_sar_log.sh"
      args:
        executable: /bin/bash  # Optional: specify the shell to use (default is /bin/sh)
      register: script_output
      ignore_errors: yes  # Optional: Ignore errors if script execution fails
      when: log_files.stdout_lines | length > 0  # Execute only if log files are present

    - name: Display script output if available
      debug:
        msg: "Script output: {{ script_output.stdout | default('No output from script.') }}"
      when: script_output.stdout is defined  # Display output only if available
